import { SayAbout1, SayAbout2, SayAbout3, SayAbout4 } from "@/assets/images";

export const sayAboutData = [
    {
        img: SayAbout1,
        name: 'Nattasha Julie',
        profession: 'Design, Australia',
        facebook: '#',
        twitter: '#',
        linkedin: '#',
        instagram: '#',
        phone: '+123 456 789',
        email: 'nH4pY@example.com',
    },
    {
        img: SayAbout2,
        name: 'Nattasha Julie',
        profession: 'Design, Australia',
        facebook: '#',
        twitter: '#',
        linkedin: '#',
        instagram: '#',
        phone: '+123 456 789',
        email: 'nH4pY@example.com',
    },
    {
        img: SayAbout3,
        name: 'Nattasha Julie',
        profession: 'Design, Australia',
        facebook: '#',
        twitter: '#',
        linkedin: '#',
        instagram: '#',
        phone: '+123 456 789',
        email: 'nH4pY@example.com',
    },
    {
        img: SayAbout4,
        name: 'Nattasha Julie',
        profession: 'Design, Australia',
        facebook: '#',
        twitter: '#',
        linkedin: '#',
        instagram: '#',
        phone: '+123 456 789',
        email: 'nH4pY@example.com',
    },
]