import type { Metadata } from "next";
import { DM_Serif_Display, Jost } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shares/Navbar";
import Footer from "@/components/shares/Footer";


const dmSerifDisplay = DM_Serif_Display({ weight: "400", subsets: ["latin"],variable: '--font-dm-serif', });
const jost = Jost({ weight: "400", subsets: ["latin"], variable: '--font-jost', });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSerifDisplay.variable} ${jost.variable} relative`}>

        <div className="w-[1px] h-full bg-gray-300 absolute left-[20%] -z-10"></div>
        <div className="w-[1px] h-full bg-gray-300 absolute left-[40%] -z-10"></div>
        <div className="w-[1px] h-full bg-gray-300 absolute left-[60%] -z-10"></div>
        <div className="w-[1px] h-full bg-gray-300 absolute right-[20%] -z-10"></div>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
